# Generated by Django 2.0.6 on 2018-08-21 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_auto_20180821_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_form3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Twelfth_marks', models.CharField(blank=True, max_length=5)),
                ('Subject1_marks', models.CharField(blank=True, max_length=5)),
                ('Subject2_marks', models.CharField(blank=True, max_length=5)),
                ('Subject3_marks', models.CharField(blank=True, max_length=5)),
                ('Subject4_marks', models.CharField(blank=True, max_length=5)),
                ('f1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_form4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenth_marksheet', models.FileField(blank=True, null=True, upload_to='')),
                ('twelfth_marksheet', models.FileField(blank=True, null=True, upload_to='')),
                ('f1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_form5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumb_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('signature_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('f1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='Subject1_marks',
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='Subject2_marks',
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='Subject3_marks',
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='Subject4_marks',
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='Twelfth_marks',
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='image',
        ),
        migrations.AddField(
            model_name='student_form2',
            name='f1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_form1',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'female'), ('O', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_form1',
            name='Nationality',
            field=models.CharField(choices=[('I', 'India'), ('N', 'Foreign')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_form1',
            name='f1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
