# Generated by Django 2.0.6 on 2018-08-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180821_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form4',
            name='twelfth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='user_%d/%Y/%m/%D/'),
        ),
    ]
