# Generated by Django 2.0.6 on 2018-08-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20180821_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form4',
            name='tenth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='u/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='student_form4',
            name='twelfth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='u/%Y/%m/%D/'),
        ),
    ]
