# Generated by Django 2.0.6 on 2018-08-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20180821_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_form4',
            old_name='user',
            new_name='f1',
        ),
    ]
