# Generated by Django 2.0.6 on 2018-08-21 16:09

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20180821_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form4',
            name='twelfth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student_form5',
            name='candidate_photo',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student_form5',
            name='signature_photo',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student_form5',
            name='thumb_photo',
            field=models.ImageField(blank=True, null=True, upload_to=student.models.user_directory_path),
        ),
    ]
