# Generated by Django 2.0.6 on 2018-08-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20180821_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_form1',
            old_name='f1',
            new_name='user',
        ),
    ]
