# Generated by Django 2.0.6 on 2018-08-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0014_auto_20180823_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_form1',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='student_form2',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='student_form3',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='student_form4',
            name='f1',
        ),
        migrations.RemoveField(
            model_name='student_form5',
            name='f1',
        ),
        migrations.AddField(
            model_name='student_form1',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_form2',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_form3',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_form4',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student_form5',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
