# Generated by Django 2.0.6 on 2018-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20180823_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form1',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'female'), ('Other', 'other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_form1',
            name='Nationality',
            field=models.CharField(choices=[('India', 'India'), ('Foreign', 'Foreign')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student_form2',
            name='Twelfth_result',
            field=models.CharField(choices=[('Awaited', 'Awaited'), ('Passed', 'Passed')], max_length=1),
        ),
    ]
