# Generated by Django 2.0.6 on 2018-08-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20180823_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_form1',
            old_name='Middel_name',
            new_name='Middle_name',
        ),
    ]
