# Generated by Django 2.0.6 on 2018-08-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20180823_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form1',
            name='Middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student_form1',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
    ]
