# Generated by Django 2.0.6 on 2018-09-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_prob_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_form3',
            name='Subject1_marks',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_form3',
            name='Subject2_marks',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_form3',
            name='Subject3_marks',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_form3',
            name='Subject4_marks',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='student_form3',
            name='marks_in_twelfth',
            field=models.CharField(max_length=5),
        ),
    ]
