# Generated by Django 2.0.6 on 2018-09-11 09:58

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_auto_20180911_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_form1',
            name='ten_marksheet',
            field=models.FileField(blank=True, upload_to=student.models.user_directory_path),
        ),
    ]
