# Generated by Django 2.0.6 on 2018-09-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0027_auto_20180911_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_form4',
            name='ref_id',
        ),
    ]
